ERROR - 2022-11-01 12:09:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\IEvent\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\IEvent\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(1360): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(1394): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\IEvent\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 C:\xampp\htdocs\IEvent\system\Database\MigrationRunner.php(167): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 C:\xampp\htdocs\IEvent\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Commands\Setup.php(308): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Commands\Setup.php(92): CodeIgniter\Shield\Commands\Setup->runMigrations()
#10 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Commands\Setup.php(79): CodeIgniter\Shield\Commands\Setup->publishConfig()
#11 C:\xampp\htdocs\IEvent\system\CLI\Commands.php(63): CodeIgniter\Shield\Commands\Setup->run(Array)
#12 C:\xampp\htdocs\IEvent\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('shield:setup', Array)
#13 C:\xampp\htdocs\IEvent\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#14 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#15 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#16 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#17 C:\xampp\htdocs\IEvent\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#18 C:\xampp\htdocs\IEvent\spark(98): CodeIgniter\CLI\Console->run()
#19 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\IEvent\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(1360): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(1394): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\IEvent\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 C:\xampp\htdocs\IEvent\system\Database\MigrationRunner.php(167): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\IEvent\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Commands\Setup.php(308): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Commands\Setup.php(92): CodeIgniter\Shield\Commands\Setup->runMigrations()
#9 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Commands\Setup.php(79): CodeIgniter\Shield\Commands\Setup->publishConfig()
#10 C:\xampp\htdocs\IEvent\system\CLI\Commands.php(63): CodeIgniter\Shield\Commands\Setup->run(Array)
#11 C:\xampp\htdocs\IEvent\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('shield:setup', Array)
#12 C:\xampp\htdocs\IEvent\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#13 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#14 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#15 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\IEvent\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#17 C:\xampp\htdocs\IEvent\spark(98): CodeIgniter\CLI\Console->run()
#18 {main}
ERROR - 2022-11-01 12:12:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\IEvent\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\IEvent\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', 'root', 'event', 3306, '', 0)
#1 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(1360): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(1394): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\IEvent\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 C:\xampp\htdocs\IEvent\system\Database\MigrationRunner.php(167): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 C:\xampp\htdocs\IEvent\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Commands\Setup.php(308): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Commands\Setup.php(92): CodeIgniter\Shield\Commands\Setup->runMigrations()
#10 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Commands\Setup.php(79): CodeIgniter\Shield\Commands\Setup->publishConfig()
#11 C:\xampp\htdocs\IEvent\system\CLI\Commands.php(63): CodeIgniter\Shield\Commands\Setup->run(Array)
#12 C:\xampp\htdocs\IEvent\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('shield:setup', Array)
#13 C:\xampp\htdocs\IEvent\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#14 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#15 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#16 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#17 C:\xampp\htdocs\IEvent\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#18 C:\xampp\htdocs\IEvent\spark(98): CodeIgniter\CLI\Console->run()
#19 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\IEvent\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(1360): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\IEvent\system\Database\BaseConnection.php(1394): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\IEvent\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 C:\xampp\htdocs\IEvent\system\Database\MigrationRunner.php(167): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\IEvent\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Commands\Setup.php(308): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Commands\Setup.php(92): CodeIgniter\Shield\Commands\Setup->runMigrations()
#9 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Commands\Setup.php(79): CodeIgniter\Shield\Commands\Setup->publishConfig()
#10 C:\xampp\htdocs\IEvent\system\CLI\Commands.php(63): CodeIgniter\Shield\Commands\Setup->run(Array)
#11 C:\xampp\htdocs\IEvent\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('shield:setup', Array)
#12 C:\xampp\htdocs\IEvent\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#13 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#14 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#15 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\IEvent\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#17 C:\xampp\htdocs\IEvent\spark(98): CodeIgniter\CLI\Console->run()
#18 {main}
ERROR - 2022-11-01 14:32:20 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\IEvent\system\Email\Email.php:1725
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1725, Array)
#1 C:\xampp\htdocs\IEvent\system\Email\Email.php(1725): mail('me@g.com', '=?UTF-8?Q?Your=...', '<p>Please use t...', 'Date: Tue, 1 No...')
#2 C:\xampp\htdocs\IEvent\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\IEvent\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Authentication\Actions\EmailActivator.php(52): CodeIgniter\Email\Email->send(false)
#5 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Controllers\ActionController.php(54): CodeIgniter\Shield\Authentication\Actions\EmailActivator->show()
#6 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Controllers\ActionController.php(42): CodeIgniter\Shield\Controllers\ActionController->show()
#7 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(926): CodeIgniter\Shield\Controllers\ActionController->_remap('show')
#8 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\ActionController))
#9 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\IEvent\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-11-01 14:32:20 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2022-11-01 14:32:20 --> 
CRITICAL - 2022-11-01 14:32:20 --> Cannot send email for user: me@g.com
Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.<br /><pre>Date: Tue, 1 Nov 2022 14:32:18 -0500
From: &lt;&gt;
Return-Path: &lt;&gt;
Reply-To: &lt;&gt;
User-Agent: CodeIgniter
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;63617442871a03.14911714&gt;
Mime-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
</pre>
in FCPATH\vendor\codeigniter4\shield\src\Authentication\Actions\EmailActivator.php on line 53.
 1 FCPATH\vendor\codeigniter4\shield\src\Controllers\ActionController.php(54): CodeIgniter\Shield\Authentication\Actions\EmailActivator->show()
 2 FCPATH\vendor\codeigniter4\shield\src\Controllers\ActionController.php(42): CodeIgniter\Shield\Controllers\ActionController->show()
 3 SYSTEMPATH\CodeIgniter.php(926): CodeIgniter\Shield\Controllers\ActionController->_remap('show')
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\ActionController))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-11-01 14:34:08 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\IEvent\system\Email\Email.php:1725
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1725, Array)
#1 C:\xampp\htdocs\IEvent\system\Email\Email.php(1725): mail('me@g.com', '=?UTF-8?Q?Your=...', '<p>Please use t...', 'Date: Tue, 1 No...')
#2 C:\xampp\htdocs\IEvent\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\IEvent\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Authentication\Actions\EmailActivator.php(52): CodeIgniter\Email\Email->send(false)
#5 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Controllers\ActionController.php(54): CodeIgniter\Shield\Authentication\Actions\EmailActivator->show()
#6 C:\xampp\htdocs\IEvent\vendor\codeigniter4\shield\src\Controllers\ActionController.php(42): CodeIgniter\Shield\Controllers\ActionController->show()
#7 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(926): CodeIgniter\Shield\Controllers\ActionController->_remap('show')
#8 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\ActionController))
#9 C:\xampp\htdocs\IEvent\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\IEvent\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-11-01 14:34:08 --> Email: Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.
ERROR - 2022-11-01 14:34:08 --> 
CRITICAL - 2022-11-01 14:34:08 --> Cannot send email for user: me@g.com
Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.<br /><pre>Date: Tue, 1 Nov 2022 14:34:06 -0500
From: &lt;&gt;
Return-Path: &lt;&gt;
Reply-To: &lt;&gt;
User-Agent: CodeIgniter
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;636174ae3c6f56.51106900&gt;
Mime-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
</pre>
in FCPATH\vendor\codeigniter4\shield\src\Authentication\Actions\EmailActivator.php on line 53.
 1 FCPATH\vendor\codeigniter4\shield\src\Controllers\ActionController.php(54): CodeIgniter\Shield\Authentication\Actions\EmailActivator->show()
 2 FCPATH\vendor\codeigniter4\shield\src\Controllers\ActionController.php(42): CodeIgniter\Shield\Controllers\ActionController->show()
 3 SYSTEMPATH\CodeIgniter.php(926): CodeIgniter\Shield\Controllers\ActionController->_remap('show')
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\ActionController))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
